controller_manager:
  ros__parameters:
    update_rate: 250  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    imu_sensor_controller:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
      publish_rate: 100
      sensor_name: "imu_sensor"

    state_estimator:
      type: quadruped_mpc/state_estimator

    gait_pattern_generator:
      type: quadruped_mpc/gait_pattern_generator

    balance_controller:
      type: quadruped_mpc/balance_controller

    foot_controller:
      type: quadruped_mpc/foot_controller


# Individual controller configurations
joint_state_broadcaster:
  ros__parameters: {}  # Empty is fine, it will auto-discover joints

imu_sensor_controller:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: imu_link

state_estimator:
  ros__parameters:
    joints:
      - fl_hip
      - fl_knee  
      - fr_hip
      - fr_knee
      - rl_hip
      - rl_knee
      - rr_hip
      - rr_knee
    state_interfaces:
      - position
      - velocity
      - effort

gait_pattern_generator:
  ros__parameters:
    # Gait type is determining the order of steps. The legs are numbered clockwise from the top left like this:
    # |1 2|
    # |4 3|
    gait_type: [2,1,1,2] #[1,3,2,4]  # Walk
    stance_duration: 0.9
    swing_duration: 0.1
    step_height: 0.1

balance_controller:
  ros__parameters:
    joints:
      - fl_hip
      - fl_knee  
      - fr_hip
      - fr_knee
      - rl_hip
      - rl_knee
      - rr_hip
      - rr_knee

foot_controller:
  ros__parameters:
    joints:
      - fl_hip
      - fl_knee  
      - fr_hip
      - fr_knee
      - rl_hip
      - rl_knee
      - rr_hip
      - rr_knee
    command_interfaces:
      - effort