# This yaml file configures the hardware interface and controllers for the robot.
# yaml files config controllers URDF files config hardware interfaces

controller_manager:
  ros__parameters:
    update_rate: 100
    robot_description: "<robot_description>"
    robot_description_semantic: "<robot_description_semantic>"
    robot_description_kinematics: "<robot_description_kinematics>"
    robot_description_planning: "<robot_description_planning>"
    robot_description_transmissions: "<robot_description_transmissions>"
    robot_description_controllers: "<robot_description_controllers>"
    hardware_plugin: "quadruped_hardware/QuadrupedHardwareInterface"


