# This yaml file configures the hardware interface and controllers for the robot.
# yaml files config controllers URDF files config hardware interfaces

controller_manager:
  ros__parameters:
    update_rate: 100
    robot_description: "<robot_description>"
    robot_description_semantic: "<robot_description_semantic>"
    robot_description_kinematics: "<robot_description_kinematics>"
    robot_description_planning: "<robot_description_planning>"
    robot_description_transmissions: "<robot_description_transmissions>"
    robot_description_controllers: "<robot_description_controllers>"
    hardware_plugin: "quadruped_hardware/QuadrupedHardwareInterface"


CANCommandController:
  ros__parameters:
    type: "quadruped_hardware/CANCommandController"
    some_parameter: some_value  # Add any necessary parameters here

ros2_control:
  ros__parameters:
    # Controller manager
    controller_manager_name: controller_manager

    hardware_parameters:

        can_interface: "can0"
        can_ids: "1,2,3,4"
        power_board_can_id: 10


    controllers:
      - name: controller_1
        type: controller_interface/YourControllerType
        hardware_components: [CAN_interface_0]
      - name: controller_2
        type: controller_interface/YourControllerType
        hardware_components: [CAN_interface_1]

