controller_manager:
  ros__parameters:
    update_rate: 50
      
    state_estimator:
      type: quadruped_mpc/state_estimator

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    joint_position_controller:
      type: position_controllers/JointPositionController

    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: joint1

    joint_group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - joint1
        - joint2

    joint_effort_controller:
      type: effort_controllers/JointEffortController
      joint: joint1

    joint_group_effort_controller:
      type: effort_controllers/JointGroupEffortController
      joints:
        - joint1
        - joint2

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - joint2
      state_publish_rate: 50
      command_interfaces:
        - position
        - velocity
        - effort
      state_interfaces:
        - position
        - velocity
        - effort
      gains:
        joint1: {p: 100.0, d: 10.0, i: 1.0}
        joint2: {p: 100.0, d: 10.0, i: 1.0}

    zero_joints_controller:
      type: quadruped_utils/ZeroJointsController



# joint_state_broadcaster:
#   ros__parameters:

#     publish_rate: 50
  #   joints:
  #     - fr_hip
  #     - fr_knee
  #     - fr_ankle
  #     - fl_hip
  #     - fl_knee
  #     - fl_ankle
  #     - rr_hip
  #     - rr_knee
  #     - rr_ankle
  #     - rl_hip
  #     - rl_knee
  #     - rl_ankle
  #   state_interfaces:
  #     - position
  #     - velocity
  #     - effort


joint_position_controller:
  ros__parameters:
      joints: 
        - fr_hip
      # interface_name: position

      command_interfaces:
        - position
      #   - velocity
      #   - effort
      #   - kp
      #   - kd
      # state_interfaces:
      #   - position
      #   - velocity
      #   - effort

joint_group_position_controller:
  ros__parameters:
      joints:
        - fr_hip
        # - fr_knee
      # interface_name: position
      command_topic: /joint_group_position_controller/command


zero_joints_controller:
  ros__parameters:

    # use doubles for all values ie 0 => 0.0
    zero_effort_lim: 1.0


    kp: 0.0
    kd: 4.0

    velocity: 0.25

    # Gains for the motor after the joint is zeroed
    zeroed_kp: 0.0 
    zeroed_kd: 0.5


    joints_orientation: [-1.0]

    joints:
      - fr_hip 
      - fr_knee

      - rr_hip
      - rr_knee

      - fl_hip 
      - fl_knee

      - rl_hip
      - rl_knee

    zero_direction: [-1.0,1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0]
      
    command_interfaces:
      - position
      - velocity
      - m_state
      - kp
      - kd
      - flip
    state_interfaces:
      - position
      - velocity
      - effort


state_estimator:
  ros__parameters:
    joints:
      - fl_hip
      - fl_knee  
      - fr_hip
      - fr_knee
      - rl_hip
      - rl_knee
      - rr_hip
      - rr_knee
    state_interfaces:
      - position
      - velocity
      - effort